### ISSUE TITLE
Too many changes in my fork

### ISSUE THREAD

**Issue by andredovale** [mikaelvesavuori/figmagic#11]
Hi Mikael,

I have forked this lib from another repo ( @smmccabe/figmagic ), because in this repo they have more implementations to process the values from Figma API.

But, currently, I have made too many changes in the project to deliver our internal product where I'm allocated. Basically, the changes I have made are:

- Source code migrated to `TypeScript`;
- Lib builded with `Rollup`;
- Tests (re)writed with `Jest`;
- Implementation of a JSON config to "teach" the lib where find the token, and, if necessary, how to process the value;
- Implementation of basic options with `yargs`.

If you are interested in the changes I have made, please see on the most recent branch: https://github.com/andredovale/figmagic/tree/feature/docs .

All this said, I opened this issue to know if you have interest to reuse my code, or, in last case, if I can change the name of lib to publish on `npm` (off course, with your permission, and all mentions of your rights).

**Comment by mikaelvesavuori** [comment]
Hi @andredovale and sorry for replying late.

Thanks for your work and happy that you are getting use of Figmagic!

I've worked on a substantial rewrite and cleanup for some time and finally got the possibility to finish my work in the weekend. Because of my own many changes, I will pass on merging any changes. However, I've taken a small number of README edits you've done and added those to mine.

Figmagic v2 has a lot more tests and uses JSDoc notation (but still MJS). I've had a number of requests both at work and online to also provide a CLI and config file setup which I've done as well, and glad to see you did something like that too.

Again, thanks for using Figmagic and I hope you'll see many of your proposed changes also in the new version even though it has no direct connection to your own work.

Closing this discussion for now, cheers.
