### ISSUE TITLE
Syncing graphics fails when there are too many images

### ISSUE THREAD

**Issue by rwproctor** [mikaelvesavuori/figmagic#167]
We have a graphics page that contains a large number of icon components.  When we go to sync our icons, we are getting the following error...

**Error: Error: Error: Missing one or more of required arguments: "figmaToken", "figmaUrl" when attempting to get data from Figma API!**

This is not the actual error however, the real issue is the request to fetch all the icons is maxing out the Figma API.  When I dump out the actual error this becomes clear.  Note the status code is a 413.  If I reduce the number of graphics the export works fine.

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/15252550/185674488-58369741-cf97-4ee9-ad92-0f1f23389c34.png">

Better error handling here would provide more meaningful information to the end user and in the case where there are just too many graphics, maybe put out a message to that effect.  Is there a suggested workaround or is there a limit to how many graphics can be exported?

Thanks,

**Comment by mikaelvesavuori** [comment]
Hi!

Improving that catch-all error message is a good idea. I'm releasing this in version `4.5.3` shortly. TBH I don't really know of a proper solution to this as it's technically outside of what I can do much about.

However I have an idea that might be functional as a workaround.

Since Figmagic can be ran with both direct commands and with configurations, it should be possible to split the icons into one or more additional files with just a Graphics page each. Then you could set up a command or script that sequentially ran Figmagic with something along the lines of `figmagic --syncGraphics --outputFolderGraphics <somethingDifferentPerRun>` and ensuring you thus don't overwrite them. Then add the run by moving all the folders generated into one and the same.

It's not beautiful but it should be workable. The scripting shouldn't be the hard part, but rather having to deal with splitting it across more files.

That's the best I can figure out on a Friday night.

**Comment by mikaelvesavuori** [comment]
`4.5.3` is out. See https://github.com/mikaelvesavuori/figmagic/releases/tag/v4.5.3

**Comment by rwproctor** [comment]
Thanks for the suggested workaround!  My first route is going to try to bring down the number of icons.  We brought in a large library which we probably don't need many of the icons.  Thanks for the quick update to 4.5.3.  Much better now ;^)

<img width="560" alt="image" src="https://user-images.githubusercontent.com/15252550/185707205-9a81cfc7-8d5b-49a0-88e0-851c21bf54d8.png">
