### ISSUE TITLE
Output Tokens to a single file

### ISSUE THREAD

**Issue by jkavalec** [mikaelvesavuori/figmagic#169]
Hi,

I can see from the docs page, that Token output showcase is a single file with 'tokens' object containing Colors and Spacing, however when I run the extraction I get multiple files as an output.

I didn't notice any settings that could switch this behavior, am I missing something?

**Comment by mikaelvesavuori** [comment]
This was an implementation example to express the idea of tokens, rather than showing the output of Figmagic. Outputting into a single file is not supported.

You can however choose to create such a file yourself that itself imports from the respective output files such as if you were creating an abstraction (like a theme).

**Comment by jkavalec** [comment]
Thank you,

I wanted to use it with Styled Components, so that is what I intended to do if I won't find option,

this is really nice project.
