### ISSUE TITLE
Transparency on color tokens

### ISSUE THREAD

**Issue by pedrorodrigopro** [mikaelvesavuori/figmagic#198]
Hi! 
I'm struggling to get my whole set of color tokens because some of them use transparency. Figma API handles colors in rgba format, where "a" stands for two-digit decimal alpha code. Issue is Figmagic fetches only the "rgb" part and builds up a hex color with it.

With 8digits hex parsing we'd get transparency digits into hex code and this way support transparent colors. Besides it's widely supported by browsers (https://caniuse.com/css-rrggbbaa). 

Thank you!

**Comment by mikaelvesavuori** [comment]
Hi @pedrorodrigopro!

Not sure I follow what the real problem is... Color values are always returned as RGB(A) values using the `[rgba()](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgb)` (legacy) syntax.

I don't see a great use-case for transitioning to hex colors.

Anyway, the transparency _should_ already be available to you.

**Comment by mikaelvesavuori** [comment]
This is now added in https://github.com/mikaelvesavuori/figmagic/releases/tag/v4.5.13

**Comment by mgolawski** [comment]
Awesome, thank you for fast resolution 👏
