### ISSUE TITLE
Feature request: Support for gradient fills

### ISSUE THREAD

**Issue by ursooperduper** [mikaelvesavuori/figmagic#73]
**Problem**
Often, style guides or design system foundations will describe not just colors, but also gradient fills. Right now, these are not supported by Figmagic which means I have to find a manual way to add that to our design tokens file. 

**Solution**
An example output I'd like to see in the colors.ts file: 
```
blackVerticalGradient:
    'linear-gradient(180deg, transparent, rgba(0, 0, 0, .02))',
```

**Additional context**
Here's the UI panel in Figma: 
<img width="249" alt="Screen Shot 2020-10-19 at 10 53 59 AM" src="https://user-images.githubusercontent.com/1380417/96468381-0ba83000-11fa-11eb-93fb-4f2c9f5a79d4.png">

**Comment by mikaelvesavuori** [comment]
Yeah, this seems to be taken care of in one the element parsers, but seemingly not during the token generation. I'll absolutely try to implement this within the week! I already have a brute copy-paste solution up and running that currently generates a linear gradient as:

```
blue4: 'linear-gradient(rgba(63, 163, 195, 255) 0%, rgba(86, 204, 242, 0) 100%)',
```

**Comment by mikaelvesavuori** [comment]
I get hard axis degree values like 0, 90 and 180 working perfectly, though my eight-grade math is too poor to fully fix this *lol*. I have a document at https://repl.it/@mikaelvesavuori/LinearGradient if anyone want to poke at solving the degrees.

**Comment by mikaelvesavuori** [comment]
Hi again. Basic support for linear gradients is now fixed (again, this kind of existed but was split into two different implementations—this is now consolidated). You should be able to get linear gradients working, but do be aware that only angles like 0, 90, 180 work perfectly, since the Figma implementation of the angle degree calculation is dependent on the box size as well. The current implementation _does not_ take that into account. With that said, expect results to differ slightly from whatever the Figma CSS values express.
